# Generated by Django 4.2.3 on 2023-08-12 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок поста')),
                ('score', models.SmallIntegerField(default=10, verbose_name='Очки за выполнение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lead_time', models.SmallIntegerField(default=3, verbose_name='Время выполнения')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Медиа файл')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Тектс сообщения')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылка',
            },
        ),
        migrations.CreateModel(
            name='SelfReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'СамоНаграда',
                'verbose_name_plural': 'СамоНаграды',
            },
        ),
        migrations.CreateModel(
            name='SelfStimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'СамоСтимул',
                'verbose_name_plural': 'СамоСтимулы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя тэга')),
                ('level', models.SmallIntegerField(default=1, verbose_name='Уровень в иерархии')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bot.tag', verbose_name='Родительский тэг')),
            ],
            options={
                'verbose_name': 'Тэг в иерархии',
                'verbose_name_plural': 'Иерархия',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('external_id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram id')),
                ('nickname', models.CharField(max_length=500, unique=True, verbose_name='TG nickname')),
                ('score', models.IntegerField(default=0, verbose_name='Опыт')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('sex', models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Мужской', max_length=7, null=True, verbose_name='Пол')),
                ('age', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Возраст')),
                ('tz_delta', models.IntegerField(blank=True, default=0, null=True, verbose_name='Разница во времени')),
                ('sign_up_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Подписан на канал')),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refs', to='bot.user', verbose_name='Пригласитель')),
                ('sub_tags', models.ManyToManyField(blank=True, related_name='sub_users', to='bot.tag', verbose_name='Подписки на тэги')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.basepost')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('technique', models.TextField(blank=True, null=True, verbose_name='Техника выполнения')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='Польза')),
                ('relevance', models.TextField(blank=True, null=True, verbose_name='Актуальность')),
                ('req_time', models.TextField(blank=True, null=True, verbose_name='Рекомендрованное время')),
                ('reqs', models.TextField(blank=True, null=True, verbose_name='Рекомендации')),
                ('media', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('media_id', models.TextField(blank=True, null=True, verbose_name='ID фото в БД телеграмма')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='Видео')),
                ('video_id', models.TextField(blank=True, null=True, verbose_name='ID видео в БД телеграмма')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='bot.tag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Привычка Виталия',
                'verbose_name_plural': 'Привычки Виталия',
            },
            bases=('bot.basepost',),
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.TimeField(default=datetime.time(7, 0), verbose_name='Утро')),
                ('noon', models.TimeField(default=datetime.time(13, 0), verbose_name='День')),
                ('evening', models.TimeField(default=datetime.time(18, 0), verbose_name='Вечер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Время дня пользователя',
                'verbose_name_plural': 'Время дня пользователя',
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Счёт выполнения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='bot.user', verbose_name='Пользователь')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='bot.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Привычка пользователя',
                'verbose_name_plural': 'Пользовательские привычки',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=15, null=True, verbose_name='День недели')),
                ('daytime', models.CharField(blank=True, choices=[('M', 'Утро'), ('N', 'День'), ('E', 'Вечер')], max_length=50, null=True, verbose_name='Время дня')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bot.sub', verbose_name='Привычка пользователя')),
            ],
            options={
                'verbose_name': 'Расписание пользователя',
                'verbose_name_plural': 'Расписание пользователя',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(related_name='user_subscriptions', through='bot.Sub', to='bot.post', verbose_name='Привычки пользователя'),
        ),
        migrations.CreateModel(
            name='DefaultSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=15, null=True, verbose_name='День недели')),
                ('daytime', models.CharField(blank=True, choices=[('M', 'Утро'), ('N', 'День'), ('E', 'Вечер')], max_length=50, null=True, verbose_name='Время дня')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='bot.post', verbose_name='Ссылка на привычку')),
            ],
            options={
                'verbose_name': 'Расписание для привычки',
                'verbose_name_plural': 'Расписание для привычки',
            },
        ),
    ]
