# Generated by Django 4.2.3 on 2023-08-12 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='bot.basepost', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(related_name='user_subscriptions', through='bot.Sub', to='bot.basepost', verbose_name='Привычки пользователя'),
        ),
    ]
