# Generated by Django 4.2.3 on 2023-08-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_sub_post_alter_user_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='time',
        ),
    ]
