# Generated by Django 4.2.3 on 2023-08-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_reward_rename_selfstimulus_stimulus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stimulus',
            options={'verbose_name': 'Стимул', 'verbose_name_plural': 'Стимул'},
        ),
        migrations.AlterField(
            model_name='user',
            name='level_rewards',
            field=models.ManyToManyField(blank=True, to='bot.levelreward', verbose_name='Level награды'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag_rewards',
            field=models.ManyToManyField(blank=True, to='bot.tagreward', verbose_name='Tag награды'),
        ),
    ]
