# Generated by Django 4.2.3 on 2023-08-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_stimulus_options_alter_user_level_rewards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level_rewards',
            field=models.ManyToManyField(blank=True, related_name='users', to='bot.levelreward', verbose_name='Level награды'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag_rewards',
            field=models.ManyToManyField(blank=True, related_name='users', to='bot.tagreward', verbose_name='Tag награды'),
        ),
    ]
