# Generated by Django 4.2.3 on 2023-08-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_user_level_rewards_alter_user_tag_rewards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagreward',
            name='tag',
        ),
        migrations.AddField(
            model_name='tagreward',
            name='tag',
            field=models.ManyToManyField(to='bot.tag', verbose_name='Тэги'),
        ),
    ]
