# Generated by Django 4.2.3 on 2023-08-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_tagreward_tag_tagreward_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagreward',
            old_name='tag',
            new_name='tags',
        ),
    ]
