# Generated by Django 4.2.3 on 2023-08-15 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_remove_tagreward_tags_tagreward_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagreward',
            name='tags',
        ),
        migrations.AddField(
            model_name='tagreward',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.tag', verbose_name='Тэг'),
            preserve_default=False,
        ),
    ]
