# Generated by Django 4.2.3 on 2023-08-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_remove_tagreward_tags_tagreward_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelreward',
            options={'verbose_name': 'Level Награда', 'verbose_name_plural': 'Награды (Level)'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Тэг в иерархии', 'verbose_name_plural': 'Иерархия'},
        ),
        migrations.AlterModelOptions(
            name='tagreward',
            options={'verbose_name': 'Tag Награда', 'verbose_name_plural': 'Награды (Tag)'},
        ),
        migrations.AddField(
            model_name='reward',
            name='name',
            field=models.CharField(default='Reward', max_length=250, verbose_name='Название награды'),
            preserve_default=False,
        ),
    ]
