# Generated by Django 4.2.3 on 2023-08-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_levelreward_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на награду'),
        ),
    ]
