# Generated by Django 4.2.3 on 2023-08-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_reward_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='day_of_week',
        ),
    ]
