# Generated by Django 4.2.3 on 2023-08-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_remove_notification_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepost',
            name='score',
            field=models.SmallIntegerField(default=5, verbose_name='Очки за выполнение'),
        ),
    ]
