# Generated by Django 4.2.3 on 2023-08-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_basepost_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_signed_up',
            field=models.BooleanField(default=False, verbose_name='Зарегистрирован ли'),
        ),
    ]
