# Generated by Django 4.2.3 on 2023-08-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_user_is_signed_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_id',
            field=models.CharField(blank=True, default='AgACAgIAAxkBAAIL2GThx4GLh0yD0qWtWpedFjWvl8dwAAI1zjEbCoIIS6FJKxT1tcASAQADAgADeQADMAQ', max_length=250, verbose_name='ID фото в БД телеграмма'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='photo_id',
            field=models.CharField(default='AgACAgIAAxkBAAIL2GThx4GLh0yD0qWtWpedFjWvl8dwAAI1zjEbCoIIS6FJKxT1tcASAQADAgADeQADMAQ', max_length=250, verbose_name='ID фото в базе телеграма'),
        ),
    ]
