# Generated by Django 4.2.3 on 2023-08-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_alter_post_benefits_alter_post_relevance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepost',
            name='lead_time',
            field=models.SmallIntegerField(default=180, verbose_name='Время выполнения (секунды)'),
        ),
    ]
