# Generated by Django 4.2.3 on 2023-08-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_alter_basepost_lead_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='TG nickname'),
        ),
    ]
