# Generated by Django 4.2.3 on 2023-08-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_alter_basepost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepost',
            options={'ordering': ('is_bodnar_post',), 'verbose_name': 'Привычка (База)', 'verbose_name_plural': 'Привычки (База)'},
        ),
    ]
