# Generated by Django 4.2.3 on 2023-08-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_alter_basepost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepost',
            options={'ordering': ('is_bot_habit',), 'verbose_name': 'Привычка (База)', 'verbose_name_plural': 'Привычки (База)'},
        ),
        migrations.RenameField(
            model_name='basepost',
            old_name='is_bodnar_post',
            new_name='is_bot_habit',
        ),
    ]
