# Generated by Django 4.2.3 on 2023-08-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_alter_basepost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basepost',
            options={'ordering': ('-is_bot_habit',), 'verbose_name': 'Привычка (База)', 'verbose_name_plural': 'Привычки (База)'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('tags__name', 'order_place'), 'verbose_name': 'Привычка (Виталия)', 'verbose_name_plural': 'Привычки (Виталия)'},
        ),
        migrations.AddField(
            model_name='post',
            name='order_place',
            field=models.SmallIntegerField(default=1, verbose_name='Порядок в очереди'),
        ),
    ]
